services:
  - type: web
    name: sistema-gerenciamento-chamados
    env: node
    plan: free
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: node dist/server.js
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
